disabled_rules:
  - type_name
  - identifier_name
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - empty_collection_literal
  - empty_string
  - fatal_error_message
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
